# Generated by Django 3.0.7 on 2020-06-21 22:01

from django.db import migrations, models
import luv_api.apps.products.models.products


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default=luv_api.apps.products.models.products.make_id, max_length=60, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('discount_value', models.FloatField(null=True)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
